name: graphose
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.9.*
  - pytorch=1.13.*
  - torchvision=0.14.*
  - pytorch-lightning=1.6.*
  - torchmetrics=0.11.0
  - torch-fidelity
  - numpy
  - matplotlib
  - tqdm
  - requests
  - opencv
  - networkx
  - albumentations
  - hydra-core=1.2.0
  - environs=9.5.0
  - pip
  - pip:
    - torch-geometric==2.3.0
    - torch-scatter
    - torch-sparse
